DROP DATABASE IF EXISTS PokemonDB;
CREATE DATABASE PokemonDB;
USE PokemonDB;

DROP TABLE IF EXISTS `Users`;
DROP TABLE IF EXISTS Pokemon;
DROP TABLE IF EXISTS Player_Pokemon;
DROP TABLE IF EXISTS Moves;
DROP TABLE IF EXISTS Pokemon_Moves;
DROP TABLE IF EXISTS Types;
DROP TABLE IF EXISTS Pokemon_Types;

CREATE TABLE `Users` (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Pokemon (
    PokemonID INT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    HP INT NOT NULL,
    Attack INT NOT NULL,
    Defense INT NOT NULL,
    Sp_Attack INT NOT NULL,
    Sp_Defense INT NOT NULL,
    Speed INT NOT NULL,
    Movement VARCHAR(50) NOT NULL,
    EV_Yield VARCHAR(50) NOT NULL,
    Catch_Rate INT NOT NULL,
    Base_Friendship INT NOT NULL,
    Base_Experience INT NOT NULL,
    Growth_Rate VARCHAR(50) NOT NULL,
);

CREATE TABLE Player_Pokemon (
    PlayerPokemonID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    PokemonID INT NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Level INT NOT NULL,
    Experience INT NOT NULL,
    Friendship INT NOT NULL,
    Move1 VARCHAR(50) DEFAULT NULL,
    Move2 VARCHAR(50) DEFAULT NULL,
    Move3 VARCHAR(50) DEFAULT NULL,
    Move4 VARCHAR(50) DEFAULT NULL,
    FOREIGN KEY (UserID) REFERENCES `Users`(UserID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (PokemonID) REFERENCES Pokemon(PokemonID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Moves (
    MoveID INT PRIMARY KEY,
    TypeID INT NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Category VARCHAR(50) NOT NULL,
    Power INT NOT NULL,
    Accuracy INT NOT NULL,
    PP INT NOT NULL,
    MakeContact BOOLEAN NOT NULL,
    FOREIGN KEY (TypeID) REFERENCES Types(TypeID) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE Pokemon_Moves (
    PokemonID INT NOT NULL,
    MoveID INT NOT NULL,
    PRIMARY KEY (PokemonID, MoveID),
    FOREIGN KEY (PokemonID) REFERENCES Pokemon(PokemonID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (MoveID) REFERENCES Moves(MoveID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Types (
    TypeID INT NOT NULL,
    Name VARCHAR(100),
    PRIMARY KEY(TypeID)
);

CREATE TABLE Pokemon_Types(
    PokemonID INT NOT NULL,
    TypeID INT NOT NULL,
    PRIMARY KEY (PokemonID,TypeID),
    FOREIGN KEY (PokemonID) REFERENCES Pokemon(PokemonID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (TypeID) REFERENCES Types(TypeID) ON DELETE SET NULL ON UPDATE CASCADE,
);